# Generated by Django 5.2.5 on 2025-08-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_stagedgenerationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRouterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='API ключ для OpenRouter', max_length=200)),
                ('model', models.CharField(default='openai/gpt-oss-20b:free', help_text='Модель для генерации ответов', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки OpenRouter',
                'verbose_name_plural': 'Настройки OpenRouter',
            },
        ),
    ]
