# Generated by Django 5.2.5 on 2025-08-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_openroutersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='generation_status_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
