# Generated by Django 5.2.5 on 2025-08-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_generation_status_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_context_boundary',
            field=models.BooleanField(default=False),
        ),
    ]
